const B2B_URL = "http://3.109.47.197:8082";

export const ROUTES = {
  APP: "/",
  LOGIN: "/login",
  RESET_PASSWORD: "/reset-password",
  PRODUCTS: "/products",
  PRICING: "/pricing",
  // BRAND_OFFERS: "/brand-offers",
  PROFILE_BUILD: "/profile-build",
  ABOUT_US: "/about-us",
  PRIVACY_POLICY: "/privacy-policy",
  COOKIE_POLICY: "/cookie-policy",
  TERMS_AND_CONDITIONS: "/terms",
  REQUEST: "/request",
  CONTACT: "/contact",
  BOQ:"/boq-assistance",
  ID: ":id",

  DASHBOARD: "/dashboard",
  UPLOAD_PROJECT: "/upload-project",
  LEADS: "/leads",
  ORDER_PLACED: "/order-placed",
  CHECKOUT: "/checkout",
  PLANS: "/plans",
  PROJECT_SUMMARY: "/project-summary",
  TAG_PROJECT: "/tag-project",
  DISCOUNT_DOCUMENT: "/dicount-document",
  BRAND: "/brand",
  BRAND_DETAILS: "/brand-details",
  MY_PROFILE: "/my-profile",
  COMPLETE_PROFILE: "/complete-profile",
  ALL_PROJECTS: "/all-projects",
  STEP_PLAN: "/step-plan",
  GO_PREMIUM: "/go-premium",
  CONTRACTOR_PROFILE: "/contractor-profile",
  ADD_PHOTOS: "/add-photos",

  BRAND_OFFERS: `${B2B_URL}/brands`,
  MAGAZINES: `${B2B_URL}/magazines`,
  PROFESSIONAL_B2B: `${B2B_URL}/findprofessionals`,
  EXPLORE_B2B: `${B2B_URL}/exploreprojects`,
};
